SELECT ugb.writer_id AS USER_ID,ugu.NICKNAME AS NICKNAME, SUM(ugb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD ugb
LEFT JOIN USED_GOODS_USER ugu on ugb.writer_id = ugu.user_id
WHERE ugb.STATUS = 'DONE'
GROUP BY ugb.writer_id
HAVING SUM(ugb.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC