SELECT YEAR(e1.DIFFERENTIATION_DATE) AS YEAR
,e2.maxSize - e1.size_of_colony AS YEAR_DEV
,e1.id AS ID
FROM ECOLI_DATA e1
JOIN (
    SELECT MAX(e2.SIZE_OF_COLONY)  AS maxSize,YEAR(DIFFERENTIATION_DATE) AS "MAX_YEAR"
    FROM ECOLI_DATA e2
    GROUP BY YEAR(e2.DIFFERENTIATION_DATE)
) e2 ON e2.MAX_YEAR = YEAR(e1.DIFFERENTIATION_DATE)
ORDER BY YEAR,YEAR_DEV