SELECT SUM(gra.SCORE) AS "SCORE",emp.EMP_NO,emp.EMP_NAME,emp.POSITION,emp.EMAIL
FROM HR_EMPLOYEES emp
JOIN HR_GRADE gra ON emp.emp_no = gra.emp_no
WHERE emp.EMP_NO = 
(
    SELECT EMP_NO FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC LIMIT 1
)
GROUP BY emp.emp_no