SELECT CONCAT("/home/grep/src/",f.BOARD_ID,"/",f.FILE_ID,f.FILE_NAME,f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE f
JOIN USED_GOODS_BOARD b ON b.board_id = f.board_id
WHERE f.board_id = (
    
    SELECT board_id FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC LIMIT 1
   )
ORDER BY file_id DESC